const state={caseId:"",version:0,view:null,queueCursor:"",receipt:null};
const $=selector=>document.querySelector(selector);
const value=(form,name)=>new FormData(form).get(name)?.toString().trim()||"";
const number=(form,name)=>Number(value(form,name));
const optionalNumber=(form,name)=>value(form,name)===""?null:Number(value(form,name));
const list=text=>text.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);
const key=()=>crypto.randomUUID();
function notice(message,error=false){const box=$("#notice");box.hidden=false;box.textContent=message;box.classList.toggle("error",error);window.clearTimeout(notice.timer);notice.timer=window.setTimeout(()=>box.hidden=true,5000)}
async function request(path,options={}){const response=await fetch(path,options);const data=await response.json().catch(()=>({error:{message:"响应不是有效 JSON"}}));if(!response.ok)throw new Error(data.error?.message||`请求失败 ${response.status}`);return data}
async function write(path,payload){return request(path,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key()},body:JSON.stringify(payload)})}
function base(payload={}){return{expectedVersion:state.version,...payload}}
function bind(id,handler){$(id).addEventListener("submit",async event=>{event.preventDefault();try{await handler(event.currentTarget);notice("操作已保存并写入审计时间线");await refresh()}catch(error){notice(error.message,true)}})}
bind("#case-form",async form=>{const result=await write("/api/cases",{siteName:value(form,"siteName"),muralLocation:value(form,"muralLocation"),materialLayers:list(value(form,"materialLayers")),pathologies:list(value(form,"pathologies")),ambientCondition:{temperatureC:number(form,"temperatureC"),humidityPercent:number(form,"humidityPercent"),lightLux:number(form,"lightLux")},actorId:value(form,"actorId")});state.caseId=result.caseId;state.version=result.version;localStorage.setItem("muralgate.caseId",state.caseId)});
bind("#baseline-form",form=>write(`/api/cases/${state.caseId}/baseline`,base({colorL:number(form,"colorL"),colorA:number(form,"colorA"),colorB:number(form,"colorB"),moisturePercent:number(form,"moisturePercent"),particleCondition:value(form,"particleCondition"),residueBaseline:number(form,"residueBaseline"),measuredAt:new Date().toISOString(),measuredBy:value(form,"measuredBy"),ambient:state.view?.case.ambientCondition||{temperatureC:21,humidityPercent:52,lightLux:85},reason:value(form,"reason")})));
bind("#zone-form",form=>write(`/api/cases/${state.caseId}/zones`,base({zoneType:value(form,"zoneType"),boundaryPoints:JSON.parse(value(form,"boundaryPoints")),areaCm2:number(form,"areaCm2"),representativeReason:value(form,"representativeReason"),controlZoneId:value(form,"controlZoneId"),actorId:value(form,"actorId")})));
bind("#protocol-form",form=>write(`/api/cases/${state.caseId}/protocols`,base({protocolId:value(form,"protocolId"),ingredients:[{name:value(form,"ingredient"),percentage:number(form,"percentage")}],concentration:number(form,"concentration"),contactSeconds:number(form,"contactSeconds"),tools:list(value(form,"tools")),removalSteps:list(value(form,"removalSteps")),safetyThresholds:{maxColorDeltaE:number(form,"maxColorDeltaE"),maxParticleLossScore:number(form,"maxParticleLossScore"),maxMoisturePercent:number(form,"maxMoisturePercent"),maxResidueValue:number(form,"maxResidueValue"),maxControlDifference:number(form,"maxControlDifference")},changeReason:value(form,"changeReason"),createdBy:value(form,"createdBy")})));
bind("#observation-form",form=>write(`/api/cases/${state.caseId}/observations`,base({zoneId:value(form,"zoneId"),protocolRevisionId:value(form,"protocolRevisionId"),roundNo:number(form,"roundNo"),observedAt:new Date().toISOString(),colorDeltaE:number(form,"colorDeltaE"),particleLossScore:number(form,"particleLossScore"),moisturePercent:number(form,"moisturePercent"),residueValue:number(form,"residueValue"),evidenceDigest:value(form,"evidenceDigest"),evidenceSummary:value(form,"evidenceSummary"),operatorId:value(form,"operatorId")})));
bind("#paired-form",form=>{const protocolRevisionId=value(form,"protocolRevisionId"),roundNo=number(form,"roundNo"),operatorId=value(form,"operatorId"),stamp=new Date().toISOString(),trialIDs=list(value(form,"trialZoneIds")),colors=list(value(form,"colorValues")).map(Number),particles=list(value(form,"particleValues")).map(Number),moistures=list(value(form,"moistureValues")).map(Number),residues=list(value(form,"residueValues")).map(Number);const observation=(zoneId,index,kind)=>({zoneId,protocolRevisionId,roundNo,observedAt:stamp,colorDeltaE:colors[index]??colors.at(-1),particleLossScore:particles[index]??particles.at(-1),moisturePercent:moistures[index]??moistures.at(-1),residueValue:residues[index]??residues.at(-1),evidenceDigest:`${kind}-${zoneId}-${roundNo}-${Date.now()}`,evidenceSummary:`${kind}同轮现场测量与影像证据`,operatorId});return write(`/api/cases/${state.caseId}/observation-batches`,base({control:observation(value(form,"controlZoneId"),0,"对照区"),trials:trialIDs.map((id,i)=>observation(id,i+1,"试验区"))}))});
bind("#remediation-form",form=>{const concentration=optionalNumber(form,"concentration"),contactSeconds=optionalNumber(form,"contactSeconds"),plannedParameters={};if(concentration!==null)plannedParameters.concentration=concentration;if(contactSeconds!==null)plannedParameters.contactSeconds=contactSeconds;return write(`/api/cases/${state.caseId}/remediations`,base({findingId:value(form,"findingId"),assignee:value(form,"assignee"),analysis:value(form,"analysis"),plannedParameters,requiredZoneIds:list(value(form,"requiredZoneIds")),dueAt:new Date(Date.now()+number(form,"dueDays")*86400000).toISOString(),actorId:value(form,"actorId")}))});
$("#remediation-queue-form").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,params=new URLSearchParams();if(value(form,"assignee"))params.set("assignee",value(form,"assignee"));if(value(form,"severity"))params.set("severity",value(form,"severity"));params.set("overdue",value(form,"overdue"));try{const data=await request(`/api/remediations?${params}`);$("#remediation-queue-results").className="";$("#remediation-queue-results").innerHTML=data.items.length?data.items.map(x=>`<button type="button" class="queue-item" data-remediation-case="${x.caseId}">${x.assignee} · ${x.ruleCode} · ${x.status} · ${new Date(x.dueAt).toLocaleString()}</button>`).join(""):"没有符合条件的整改任务";$("#remediation-queue-results").querySelectorAll("[data-remediation-case]").forEach(button=>button.addEventListener("click",async()=>{state.caseId=button.dataset.remediationCase;localStorage.setItem("muralgate.caseId",state.caseId);await refresh()}))}catch(error){notice(error.message,true)}});
bind("#selection-form",form=>write(`/api/cases/${state.caseId}/candidate-selection`,base({protocolRevisionId:value(form,"protocolRevisionId"),reason:value(form,"reason"),reviewerId:value(form,"reviewerId")})));
bind("#freeze-form",form=>write(`/api/cases/${state.caseId}/freeze`,base({protocolRevisionId:value(form,"protocolRevisionId"),reviewerId:value(form,"reviewerId"),reviewNote:value(form,"reviewNote")})));
bind("#permit-form",form=>{const expires=new Date(Date.now()+number(form,"days")*86400000);return write(`/api/cases/${state.caseId}/permit`,base({scope:value(form,"scope"),restrictions:list(value(form,"restrictions")),issuedBy:value(form,"issuedBy"),expiresAt:expires.toISOString()}))});
bind("#verify-form",async form=>{const data=await request(`/api/permits/${encodeURIComponent(value(form,"permitNumber"))}/verify`);state.receipt=data;$("#receipt-download").hidden=false;$("#verification-results").innerHTML=`<div class="risk ${data.valid?"closed":"open"}"><b>${data.message}</b><br>状态：${data.validity} · 剩余 ${data.remainingDays} 天<br>范围：${data.permit.scope}<br>限制：${data.permit.restrictions.join("；")||"无"}<br>${data.checks.map(check=>`${check.passed?"✓":"✗"} ${check.code}：${check.reason}`).join("<br>")}</div>`;notice(data.message,!data.valid)});
$("#receipt-download").addEventListener("click",()=>{if(!state.receipt)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state.receipt,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`许可验真回执-${state.receipt.permit?.permitNumber||"unknown"}.json`;link.click();URL.revokeObjectURL(url)});
function render(view,events){state.view=view;state.version=view.case.version;$("#case-label").textContent=view.case.siteName;$("#case-state").textContent=`${view.case.status.toUpperCase()} · v${view.case.version}`;const controls=view.zones.filter(z=>z.zoneType==="control"),trials=view.zones.filter(z=>z.zoneType==="trial"),latest=view.protocols.at(-1);if(controls[0]){$("#control-zone").value=controls[0].zoneId;$("#paired-control").value=controls[0].zoneId}if(trials.length)$("#paired-trials").value=trials.map(x=>x.zoneId).join(",");if(latest){$("#observation-protocol").value=latest.revisionId;$("#paired-protocol").value=latest.revisionId;$("#freeze-protocol").value=latest.revisionId;$("#selection-protocol").value=latest.revisionId}if(!$("#observation-zone").value&&controls[0])$("#observation-zone").value=controls[0].zoneId;if(view.permit){$("#permit-number").value=view.permit.permitNumber}$("#summary").className="";$("#summary").innerHTML=`<div class="metric"><span>基线</span><strong>${view.baseline?"v"+view.baseline.revisionNo:"未提交"}</strong></div><div class="metric"><span>分区</span><strong>${trials.length} 试验 / ${controls.length} 对照</strong></div><div class="metric"><span>方案修订</span><strong>${view.protocols.length}</strong></div><div class="metric"><span>观察证据</span><strong>${view.observations.length}</strong></div><div class="metric"><span>开放风险</span><strong>${view.findings.filter(x=>x.status==="open"&&!x.historical).length}</strong></div>${view.baselines.filter(x=>x.impact).map(x=>`<div class="risk closed"><b>基线 v${x.revisionNo} 影响摘要</b><br>${x.impact.summary}</div>`).join("")}${view.findings.map(x=>`<div class="risk ${x.status}"><b>${x.ruleCode}${x.historical?"（历史）":""}</b><br>${x.message}<br><small>${x.historical?"历史结论":x.status==="open"?"待整改":"已闭环"}</small></div>`).join("")}${view.remediations.map(x=>`<div class="risk ${x.status==="resolved"?"closed":"open"}"><b>整改：${x.ruleCode}</b><br>${x.assignee} · ${x.status} · ${new Date(x.dueAt).toLocaleDateString()}</div>`).join("")}${view.permit?`<div class="risk closed"><b>${view.permit.permitNumber}</b><br>许可已签发，可在下方独立验真。</div>`:""}`;$("#timeline").innerHTML=`<h3>审计时间线</h3>${events.map(e=>`<div class="event"><b>${e.summary}</b><small>#${e.sequence} · ${e.actorId} · ${new Date(e.createdAt).toLocaleString()}</small></div>`).join("")}`}
function renderCandidates(data){$("#candidate-results").className="";$("#candidate-results").innerHTML=data.candidates.length?data.candidates.map(x=>`<div class="risk ${x.eligible?"closed":"open"}"><b>${x.protocolId} · v${x.revisionNo}</b><br>覆盖 ${x.coveredPairs}/${x.requiredPairs} · 开放阻断 ${x.openBlockers}<br>${x.metrics.map(m=>`${m.code} 裕量 ${m.worstMargin} / 对照差 ${m.worstControlDifference}`).join("；")}<br>${x.gaps.join("；")||"证据完整，可入围"}</div>`).join(""):"尚无候选方案"}
async function refresh(){if(!state.caseId)return;try{const [view,audit,candidates]=await Promise.all([request(`/api/cases/${state.caseId}`),request(`/api/cases/${state.caseId}/audit`),request(`/api/cases/${state.caseId}/candidates`)]);render(view,audit.events);renderCandidates(candidates);await loadQueue(false)}catch(error){notice(error.message,true)}}
async function loadQueue(useCursor=false){const form=$("#queue-form"),params=new URLSearchParams(),status=value(form,"status"),keyword=value(form,"keyword");if(status)params.set("status",status);if(keyword)params.set("keyword",keyword);params.set("limit",String(number(form,"limit")||10));if(useCursor&&state.queueCursor)params.set("cursor",state.queueCursor);const data=await request(`/api/cases?${params}`);state.queueCursor=data.nextCursor||"";$("#queue-next").hidden=!state.queueCursor;$("#queue-results").className="";$("#queue-results").innerHTML=data.items.length?data.items.map(x=>`<button type="button" class="queue-item" data-case-id="${x.case.caseId}">${x.case.siteName} · ${x.case.muralLocation} · ${x.case.status} · v${x.case.version} · 基线 v${x.currentRevision||0} · 阻断 ${x.openBlockers}${x.permitValidity?` · 许可 ${x.permitValidity}`:""}</button>`).join(""):`没有符合条件的案卷（共 ${data.total} 个）`;$("#queue-results").querySelectorAll("[data-case-id]").forEach(button=>button.addEventListener("click",async()=>{state.caseId=button.dataset.caseId;localStorage.setItem("muralgate.caseId",state.caseId);await refresh()}))}
$("#queue-form").addEventListener("submit",async event=>{event.preventDefault();state.queueCursor="";try{await loadQueue(false)}catch(error){notice(error.message,true)}});$("#queue-next").addEventListener("click",async()=>{try{await loadQueue(true)}catch(error){notice(error.message,true)}});
document.querySelectorAll("[data-jump]").forEach(button=>button.addEventListener("click",()=>document.getElementById(button.dataset.jump).scrollIntoView({behavior:"smooth",block:"start"})));$("#refresh").addEventListener("click",refresh);
async function boot(){try{await request("/healthz");$(".health").classList.add("ready");$("#health-text").textContent="服务与存储正常"}catch{$("#health-text").textContent="服务检查失败"}state.caseId=localStorage.getItem("muralgate.caseId")||"";await loadQueue(false);await refresh()}boot();
